# Generated by Django 3.2.1 on 2021-05-20 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0002_mascota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='descripion',
            new_name='descripcion',
        ),
    ]
