# Generated by Django 3.2.1 on 2021-05-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0003_rename_descripion_mascota_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(null=True, upload_to='mascotas'),
        ),
    ]
