# Generated by Django 3.2.1 on 2021-05-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0004_mascota_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(null=True, upload_to='cate'),
        ),
    ]
