# Generated by Django 3.2.1 on 2021-05-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0005_categoria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
