# Generated by Django 3.2.1 on 2021-05-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0006_mascota_publicar'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='comentario',
            field=models.TextField(default='--'),
        ),
    ]
