# Generated by Django 3.2.1 on 2021-05-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0007_mascota_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(default='mascotas/no_disponible.jpg', upload_to='mascotas'),
        ),
    ]
