# Generated by Django 3.2.1 on 2021-05-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0008_alter_mascota_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='usuario',
            field=models.CharField(default='--', max_length=45),
        ),
    ]
