# Generated by Django 3.2.1 on 2021-06-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0010_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='dueno',
            field=models.CharField(default='--', max_length=45),
        ),
    ]
